### ISSUE TITLE
Frontend Components Structure

### ISSUE THREAD

**Issue by L0Lmaker** [cpsc455-bugstorm/TravelersTea#51]
- [x] Sidebar #56 @L0Lmaker 
  - [x] Preferences (Modal) #53 
    - [x] Views
    - [x] Compact, Non-compact
  - [x] Signout Button #57 @vee-16 
- [x] #79  @AndyLiang1 
  - [x] Pin for Map
- [x] Timeline @Graywing13 #78 
  - [x] Trip View (Set of days)
  - [x] Day View (Set of Stages in a day)
- [x] #58 @NLmeng 
- [x] #60  @NLmeng 
  - Destination (City), Stages per day, Budget, Number of Days
- [x] #70  @NLmeng 
  - Destination (City), Stages per day, Budget, Number of Days
- [x] Edit Stage Form #55 @L0Lmaker 
- [x] Login Screen #57 @vee-16

**Comment by L0Lmaker** [comment]
Please create issues and link them in the checklist
